"""All LLM prompt templates for CodeDoc."""


def system_prompt(config) -> str:
    notes_section = ""
    if config.notes:
        notes_section = f"\n\nProject context:\n{config.notes}"

    instructions_section = ""
    if config.instructions:
        instructions_section = f"\n\nSpecial instructions:\n{config.instructions}"

    return f"""You are CodeDoc, an AI agent that reads source code files and builds a structured Markdown reference document for a codebase.

Your job is to understand what each file does, how it connects to others, and to incrementally build a doc that gives any reader a complete abstract picture of the system.

You always respond with valid JSON only. No preamble, no explanation, no markdown fences. Your response must be a single JSON object that can be parsed directly.

Key concepts:
- A "wire" is an unresolved reference — something a file depends on that hasn't been documented yet.
- When you see a file import, call, or reference something not yet documented, you "open a wire".
- When a later file documents the other end, the wire is "closed".
- Your goal is to trace all connections and build a complete picture.

When writing documentation content:
- Be precise and technical but readable
- Focus on WHAT the code does, HOW it connects to other parts, and WHY it exists
- Include key function/class/export names
- Note important patterns, data flows, and architectural decisions
- Use cross-references like "→ See [Section Name]" when referencing other documented parts{notes_section}{instructions_section}"""


def triage_prompt(
    file_tree: str,
    all_files: list,
    md_contents: dict = None,
    notes: str = "",
    instructions: str = "",
) -> str:
    """
    Triage prompt — AI decides what to document.
    Only sees file paths. NO file content. Cheap call.
    """
    md_section = ""
    if md_contents:
        md_section = "\n\n## Existing Documentation (for context)\n"
        for path, content in list(md_contents.items())[:3]:
            md_section += f"\n### {path}\n{content[:500]}\n"

    notes_section = ""
    if notes:
        notes_section = f"\n\n## Project Notes from User\n{notes}"

    instructions_section = ""
    if instructions:
        instructions_section = f"\n\n## Special Instructions\n{instructions}"

    file_count = len(all_files)

    return f"""You are triaging a codebase before documentation. Your job is to decide which files are worth reading and which are generated boilerplate that would waste tokens.

## File Tree ({file_count} files total)
{file_tree}

{md_section}{notes_section}{instructions_section}

## Your Task

Look at the file tree and classify everything into three categories:

### CORE (document fully)
Files a developer WROTE and would need to understand. Application logic, business rules, data models, services, routes, components, utilities, scripts with real logic.

### SKIM (read lightly)
Config and manifest files that provide useful context but don't need deep documentation. Package managers, build configs, CI/CD, Docker configs, linters, formatters.

### SKIP (ignore completely)  
Files that are:
- **Generated by frameworks** (Flutter's ios/, android/, windows/, linux/, macos/, web/ platform folders; React Native's android/app/src/main/res/; .next/ build output)
- **Generated by tools** (*.g.dart, *.freezed.dart, migrations with just timestamps, compiled output)
- **Lock files** (package-lock.json, pubspec.lock, yarn.lock, Cargo.lock, etc.)
- **IDE/editor files** (.idea/, .vscode/ settings)
- **Build artifacts** (build/, dist/, out/, target/, bin/, obj/)
- **Dependency directories** (node_modules/, Pods/, .dart_tool/)
- **Asset files** (images, fonts, icons — unless they're SVG components)
- **Test files** (unless user specifically asked for tests)

## Important Rules

1. **Use directory patterns when possible.** If an entire directory should be skipped, just say "ios/" instead of listing every file.
2. **Be aggressive with SKIP.** When in doubt, skip. It's better to miss a boilerplate file than to waste tokens on generated code.
3. **Platform folders in cross-platform projects are almost always SKIP.** In Flutter: ios/, android/, windows/, linux/, macos/, web/ are 95% generated. Only flag specific files as warnings if they MIGHT have custom code (e.g., AppDelegate.swift, build.gradle).
4. **The user can override you.** So err on the side of skipping — they'll pull things back in if needed.

## Response Format

Return a JSON object:

```json
{{
    "project_type": "flutter | react_native | nextjs | django | express | ...",
    "core": ["lib/", "src/services/", "specific_file.py"],
    "skim": ["pubspec.yaml", "Dockerfile", "docker-compose.yml"],
    "skip": ["ios/", "android/", "build/", "*.lock", "web/"],
    "reasoning": "One sentence explaining your classification logic",
    "warnings": [
        "ios/Runner/AppDelegate.swift might have custom push notification setup",
        "android/app/build.gradle has custom flavors that affect builds"
    ]
}}
The warnings array should flag files inside SKIP directories that a developer MIGHT have customized. The user will see these and can pull them into CORE if needed.

Respond with ONLY the JSON object."""

def planning_prompt(
    file_tree: str,
    md_contents: dict,
    files: list,
    entry_hint: str = None,
) -> str:
    md_section = ""
    if md_contents:
        md_section = "\n\n## Existing Documentation\n"
        for path, content in md_contents.items():
            md_section += f"\n### {path}\n{content[:2000]}\n"

    entry_section = ""
    if entry_hint:
        entry_section = (
            f"\n\nEntry hint from user: The main entry point is likely `{entry_hint}`."
        )

    files_list = "\n".join(f"- {f}" for f in files)

    return f"""Analyze this codebase structure and plan the optimal file processing order for documentation.

## File Tree
{file_tree}

## Files to Process
{files_list}
{md_section}{entry_section}

## Your Task

Return a JSON object with:

1. **order**: An array of file paths in the order they should be processed. Start with entry points, config files, or foundational modules. Then proceed through the dependency chain so that when you read each file, you already have context from its dependencies.

2. **parked**: An array of file paths that should be processed last because they have unclear purpose or dependencies that can only be understood after seeing other files first.

3. **park_reasons**: An object mapping each parked file path to a reason string.

4. **skeleton**: An object with:
   - **doc_title**: A descriptive title for the codebase documentation
   - **suggested_sections**: An array of section names that would logically organize this codebase's documentation

Base your ordering on:
- Start from entry points (main files, index files, app bootstrap)
- Then core models/types/schemas
- Then business logic / services
- Then routes / controllers / handlers
- Then utilities / helpers
- Then config / scripts / misc

Respond with ONLY the JSON object."""

def processing_prompt(
    file_path: str,
    file_content: str,
    relevant_sections: dict,
    open_wires: list,
    section_index: dict,
) -> str:
    sections_text = ""
    if relevant_sections:
        sections_text = "\n\n## Relevant Documentation So Far\n"
        for sec_id, sec in relevant_sections.items():
            sections_text += (
                f"\n### {sec.get('title', sec_id)}\n{sec.get('content', '')}\n"
            )

    wires_text = ""
    if open_wires:
        wires_text = "\n\n## Currently Open Wires (unresolved references)\n"
        for w in open_wires:
            wires_text += (
                f"- Wire {w['id']}: {w['from']} → {w['to']} "
                f"({w['type']}) — {w.get('context', 'no context')}\n"
            )

    index_text = "\n\n## Section Index (all documented sections)\n"
    if section_index:
        for sid, meta in section_index.items():
            tags = ", ".join(meta.get("tags", []))
            index_text += (
                f"- **{meta.get('title', sid)}** [{sid}] "
                f"(file: {meta.get('file', '?')}, tags: {tags})\n"
            )
    else:
        index_text += "(No sections documented yet)\n"

    return f"""Read this source file and produce documentation updates.

## File: `{file_path}`
{file_content}

{sections_text}{wires_text}{index_text}

## Your Task

Analyze this file and return a JSON object with:

1. **new_section**: A new documentation section for this file (or null if merging). Object with:
   - **id**: kebab-case identifier
   - **title**: Human-readable title
   - **content**: Markdown documentation content
   - **tags**: Array of relevant tags
   - **insert_after**: section_id or null

2. **patches**: Array of updates to existing sections. Each: {{"section_id": "str", "update_type": "append|replace|insert_link", "content": "str"}}

3. **wires_closed**: Array of wire IDs this file resolves.

4. **wires_opened**: Array of NEW wires. Each: {{"to": "filepath or symbol", "type": "import|call|model|config|event|unknown", "context": "why this matters"}}

5. **unpark**: Array of file paths that should now be unparked.

6. **park_new**: Array of {{"path": "str", "reason": "str"}}.

Respond with ONLY the JSON object."""


def finalize_prompt(
    section_index: dict,
    open_wires: list,
    parked_summaries: dict,
) -> str:
    index_text = "## All Documented Sections\n"
    for sid, meta in section_index.items():
        tags = ", ".join(meta.get("tags", []))
        index_text += (
            f"- **{meta.get('title', sid)}** [{sid}] "
            f"(file: {meta.get('file', '?')}, tags: {tags})\n"
        )

    wires_text = "## Remaining Open Wires\n"
    if open_wires:
        for w in open_wires:
            wires_text += (
                f"- Wire {w['id']}: {w['from']} → {w['to']} "
                f"({w['type']}) — {w.get('context', '')}\n"
            )
    else:
        wires_text += "(None — all wires resolved!)\n"

    parked_text = ""
    if parked_summaries:
        parked_text = "\n## Parked Files (briefly analyzed)\n"
        for path, summary in parked_summaries.items():
            parked_text += f"\n### {path}\n{summary[:1000]}\n"

    return f"""Finalization pass for the codebase documentation.

{index_text}

{wires_text}

{parked_text}

## Your Task

Return a JSON object with:

1. **overview**: Comprehensive overview markdown — what this project is, architecture, tech stack, how components fit together, entry points for new developers.

2. **section_updates**: Array of patches to existing sections for final cross-references. Each: {{"section_id": "str", "update_type": "append", "content": "str"}}

3. **wire_classifications**: For each open wire, classify it. Array of: {{"wire_id": "str", "classification": "external_package|missing_file|dead_code|config_dependency|unknown", "note": "str"}}

Respond with ONLY the JSON object."""

def skeleton_prompt(
    file_path: str,
    skeleton_content: str,
    section_index: dict,
    open_wires: list,
) -> str:
    """Prompt for the skeleton pass on a large file."""
    index_text = "\n\n## Section Index\n"
    if section_index:
        for sid, meta in section_index.items():
            tags = ", ".join(meta.get("tags", []))
            index_text += (
                f"- **{meta.get('title', sid)}** [{sid}] "
                f"(file: {meta.get('file', '?')}, tags: {tags})\n"
            )

    wires_text = ""
    if open_wires:
        wires_text = "\n\n## Open Wires\n"
        for w in open_wires[:30]:
            wires_text += (
                f"- Wire {w['id']}: {w['from']} → {w['to']} "
                f"({w['type']}) — {w.get('context', '')}\n"
            )

    return f"""This is a LARGE file. You are seeing only the SKELETON — imports, signatures, docstrings, no function bodies.

Your job: create a preliminary documentation section and identify all connections (wires) from this skeleton alone.

## File: `{file_path}` (skeleton only)
{skeleton_content}

{index_text}{wires_text}

## Your Task

Return a JSON object with:

1. **new_section**: Create a preliminary section:
   - **id**: kebab-case identifier
   - **title**: Descriptive title
   - **content**: Document what you CAN determine from signatures and imports:
     - File purpose / responsibility
     - List of classes and their apparent roles
     - List of key functions and their signatures
     - Mark each with "⏳ detail pending" where you need to see the body
   - **tags**: Relevant tags
   - **insert_after**: section_id or null

2. **patches**: Patches to existing sections (cross-references you can already see)

3. **wires_closed**: Wire IDs resolved by seeing this file's exports/signatures

4. **wires_opened**: New wires from imports and references in this skeleton

5. **interesting_symbols**: Array of function/class names whose bodies you'd most want to see for documentation. Prioritize:
   - Functions that close open wires
   - Functions called from many places
   - Functions with complex signatures
   - Skip obvious getters/setters/boilerplate

6. **unpark**: Files to unpark
7. **park_new**: Files to park

Respond with ONLY the JSON object."""


def detail_prompt(
    file_path: str,
    chunk_content: str,
    chunk_label: str,
    chunk_index: int,
    total_chunks: int,
    skeleton_section_id: str,
    skeleton_content: str,
    open_wires: list,
) -> str:
    """Prompt for a detail pass on a chunk of a large file."""
    wires_text = ""
    if open_wires:
        wires_text = "\n\n## Relevant Open Wires\n"
        for w in open_wires[:15]:
            wires_text += (
                f"- Wire {w['id']}: {w['from']} → {w['to']} "
                f"({w['type']}) — {w.get('context', '')}\n"
            )

    return f"""This is a DETAIL PASS on chunk {chunk_index + 1}/{total_chunks} of a large file.

You already created a skeleton section for this file. Now you're reading the actual code in one section. Update the skeleton section with real understanding from this code.

## File: `{file_path}` — {chunk_label}
{chunk_content}


## Existing Skeleton Section [{skeleton_section_id}]
{skeleton_content}
{wires_text}

## Your Task

Return a JSON object with:

1. **patches**: Array of patches to the skeleton section [{skeleton_section_id}]:
   - Replace "⏳ detail pending" markers with actual documentation
   - Add data flow descriptions, business logic explanations
   - Add cross-references to other sections
   Each: {{"section_id": "{skeleton_section_id}", "update_type": "append|replace", "content": "str"}}

2. **wires_closed**: Wire IDs resolved by this chunk's code

3. **wires_opened**: New wires discovered in this chunk's code

4. **unpark**: Files to unpark
5. **park_new**: Files to park

Focus on WHAT this code does and HOW it connects to other parts. Don't just describe syntax — explain purpose, data flow, and business logic.

Respond with ONLY the JSON object."""

